version: "2.3.3"

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 1546
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
    build:
      dockerfile: ./dbdockerfile/Dockerfile
  football_marketplace:
    build:
      dockerfile: Dockerfile
    ports:
      - 3300:3300
    depends_on:
      - "postgres"
  reactjs:
    build:
      dockerfile: ./football_marketplace-app/frontend/Dockerfile
    ports:
      - 3000:3000
